
name: CI Workflow

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    name: CI JOB
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0


      - name: dotnet test
        run: dotnet test -c Release 
      
      - name: dotnet publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj -c Release -o artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: GitHubActionsDotNet-Api
          path: artifacts/

