
name: run every 5 minute workflow

on:
   schedule:
    - cron: '*/5 * * * *'


jobs:
  cron:
    name: run every 5 minutes job
    runs-on: ubuntu-latest

    steps:
      - name: hellow world
        run: echo "hello world"