name: secrets workflow

on:
  workflow_dispatch:

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  secrets:
    name: Secretes Job
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:
      - name: echo environment variables
        run: echo "$JOB_NAME and $API_CSPROJ_PATH"
